// <auto-generated />
using System;
using AppQLHui.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppQLHui.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260409104317_AddOtherDeductionNoteToDraw")]
    partial class AddOtherDeductionNoteToDraw
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppQLHui.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BankAccountName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BankAccountNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BankName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AppQLHui.Models.Draw", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ActualReceived")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal>("BidAmount")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal>("CollectedFee")
                        .HasColumnType("decimal(18,0)");

                    b.Property<DateTime>("DrawDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("OldDebtDeduction")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal>("OtherDeduction")
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("OtherDeductionNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("int");

                    b.Property<int>("TontineId")
                        .HasColumnType("int");

                    b.Property<int?>("WinningShareId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TontineId");

                    b.HasIndex("WinningShareId");

                    b.ToTable("Draws");
                });

            modelBuilder.Entity("AppQLHui.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BankAccountName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BankAccountNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BankName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ZaloName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("AppQLHui.Models.Tontine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaseAmount")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal>("CommissionFee")
                        .HasColumnType("decimal(18,0)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CycleNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CycleType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("FeeType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalFeesCollected")
                        .HasColumnType("decimal(18,0)");

                    b.Property<int>("TotalShares")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Tontines");
                });

            modelBuilder.Entity("AppQLHui.Models.TontineShare", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsSettledEarly")
                        .HasColumnType("bit");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TontineId")
                        .HasColumnType("int");

                    b.Property<int?>("WonDrawId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TontineId");

                    b.HasIndex("WonDrawId");

                    b.ToTable("TontineShares");
                });

            modelBuilder.Entity("AppQLHui.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountPay")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal>("AmountReceive")
                        .HasColumnType("decimal(18,0)");

                    b.Property<int>("DrawId")
                        .HasColumnType("int");

                    b.Property<bool>("IsSettled")
                        .HasColumnType("bit");

                    b.Property<decimal>("NetTotal")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("NetAmount");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("decimal(18,0)");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DrawId");

                    b.HasIndex("PlayerId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("AppQLHui.Models.ZaloSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AutoCopyBill")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSingleSendOnly")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<string>("PasteShortcut")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PasteX")
                        .HasColumnType("int");

                    b.Property<int>("PasteY")
                        .HasColumnType("int");

                    b.Property<int>("SendDelayMs")
                        .HasColumnType("int");

                    b.Property<string>("SendShortcut")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("ZaloSettings");
                });

            modelBuilder.Entity("AppQLHui.Models.Draw", b =>
                {
                    b.HasOne("AppQLHui.Models.Tontine", "Tontine")
                        .WithMany("Draws")
                        .HasForeignKey("TontineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppQLHui.Models.TontineShare", "WinningShare")
                        .WithMany()
                        .HasForeignKey("WinningShareId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Tontine");

                    b.Navigation("WinningShare");
                });

            modelBuilder.Entity("AppQLHui.Models.Player", b =>
                {
                    b.HasOne("AppQLHui.Models.AppUser", "Owner")
                        .WithMany("Players")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("AppQLHui.Models.Tontine", b =>
                {
                    b.HasOne("AppQLHui.Models.AppUser", "Owner")
                        .WithMany("Tontines")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("AppQLHui.Models.TontineShare", b =>
                {
                    b.HasOne("AppQLHui.Models.Player", "Player")
                        .WithMany("TontineShares")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AppQLHui.Models.Tontine", "Tontine")
                        .WithMany("Shares")
                        .HasForeignKey("TontineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AppQLHui.Models.Draw", "WonDraw")
                        .WithMany("WonShares")
                        .HasForeignKey("WonDrawId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Player");

                    b.Navigation("Tontine");

                    b.Navigation("WonDraw");
                });

            modelBuilder.Entity("AppQLHui.Models.Transaction", b =>
                {
                    b.HasOne("AppQLHui.Models.Draw", "Draw")
                        .WithMany("Transactions")
                        .HasForeignKey("DrawId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppQLHui.Models.Player", "Player")
                        .WithMany("Transactions")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Draw");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("AppQLHui.Models.ZaloSettings", b =>
                {
                    b.HasOne("AppQLHui.Models.AppUser", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("AppQLHui.Models.AppUser", b =>
                {
                    b.Navigation("Players");

                    b.Navigation("Tontines");
                });

            modelBuilder.Entity("AppQLHui.Models.Draw", b =>
                {
                    b.Navigation("Transactions");

                    b.Navigation("WonShares");
                });

            modelBuilder.Entity("AppQLHui.Models.Player", b =>
                {
                    b.Navigation("TontineShares");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("AppQLHui.Models.Tontine", b =>
                {
                    b.Navigation("Draws");

                    b.Navigation("Shares");
                });
#pragma warning restore 612, 618
        }
    }
}
