// <auto-generated />
using System;
using AppQLHui.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppQLHui.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260402144003_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("AppQLHui.Models.Draw", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BidAmount")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal>("CollectedFee")
                        .HasColumnType("decimal(18,0)");

                    b.Property<DateTime>("DrawDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TontineId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WinningShareId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TontineId");

                    b.HasIndex("WinningShareId");

                    b.ToTable("Draws");
                });

            modelBuilder.Entity("AppQLHui.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ZaloName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("AppQLHui.Models.Tontine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BaseAmount")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal>("CommissionFee")
                        .HasColumnType("decimal(18,0)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("FeeType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalShares")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Tontines");
                });

            modelBuilder.Entity("AppQLHui.Models.TontineShare", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TontineId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WonDrawId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TontineId");

                    b.HasIndex("WonDrawId");

                    b.ToTable("TontineShares");
                });

            modelBuilder.Entity("AppQLHui.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AmountPay")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal>("AmountReceive")
                        .HasColumnType("decimal(18,0)");

                    b.Property<int>("DrawId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSettled")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("NetTotal")
                        .HasColumnType("decimal(18,0)");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DrawId");

                    b.HasIndex("PlayerId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("AppQLHui.Models.Draw", b =>
                {
                    b.HasOne("AppQLHui.Models.Tontine", "Tontine")
                        .WithMany("Draws")
                        .HasForeignKey("TontineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppQLHui.Models.TontineShare", "WinningShare")
                        .WithMany()
                        .HasForeignKey("WinningShareId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Tontine");

                    b.Navigation("WinningShare");
                });

            modelBuilder.Entity("AppQLHui.Models.TontineShare", b =>
                {
                    b.HasOne("AppQLHui.Models.Player", "Player")
                        .WithMany("TontineShares")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AppQLHui.Models.Tontine", "Tontine")
                        .WithMany("Shares")
                        .HasForeignKey("TontineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppQLHui.Models.Draw", "WonDraw")
                        .WithMany("WonShares")
                        .HasForeignKey("WonDrawId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Player");

                    b.Navigation("Tontine");

                    b.Navigation("WonDraw");
                });

            modelBuilder.Entity("AppQLHui.Models.Transaction", b =>
                {
                    b.HasOne("AppQLHui.Models.Draw", "Draw")
                        .WithMany("Transactions")
                        .HasForeignKey("DrawId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppQLHui.Models.Player", "Player")
                        .WithMany("Transactions")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Draw");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("AppQLHui.Models.Draw", b =>
                {
                    b.Navigation("Transactions");

                    b.Navigation("WonShares");
                });

            modelBuilder.Entity("AppQLHui.Models.Player", b =>
                {
                    b.Navigation("TontineShares");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("AppQLHui.Models.Tontine", b =>
                {
                    b.Navigation("Draws");

                    b.Navigation("Shares");
                });
#pragma warning restore 612, 618
        }
    }
}
